output: "output/test" # "output/apiin_bu_25_ppm"
data_path: "input_data"
meta_file: "input_data/metadata_filtered.csv"
internal_standard: "C7H8O2"
is_adduct: "[M-H]-"
ppm_global: 25
sn_threshold: 10
mzdiff: 0.01
beta_cor_threshold: 0.8
beta_snr_threshold: 3
bw_first_grouping: 3
peak_anchor_sd: 1
min_fraction_align: 0.9
extra_peaks: 0
span: 0.6
bw_second_grouping: 0.5
missingness: 50
gap_filling: "norm_fill_imp"
qvalue: 0.05
polarity: "negative"
biotransf_file: "biotransformations.csv"
rpairs_path: "scripts/search_compounds/output/rpairs.tsv"
glycoside: "C26H28O14"
aglycone: "C15H10O5"
ppm_match: 5
all_vs_all: false
smiles: "C1=CC(=CC=C1C2=CC(=O)C3=C(C=C(C=C3O2)O)O)O"
biot_dir: "biotransformer3.0jar"
seed: 123
cores: 10 # -1


