[workspace]
authors = ["Wilhelm Sjöland <wilhelmsjoland@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "metabolite_disco"
platforms = ["osx-arm64"] # was osx-arm64 — switched because rcdk/rJava/this.path have no arm64 builds
version = "0.1.0"

[tasks]

[dependencies]
r-base = "4.5.3.*"
python = "3.14.6.*"
snakemake = "9.23.1.*"
bioconductor-biocparallel = "==1.44.0"
r-cli = "==3.6.5"
r-dplyr = "==1.2.0"
r-purrr = "==1.2.1"
r-rcolorbrewer = "==1.1.3"
r-readr = "==2.2.0"
r-rsqlite = "==2.4.6"
r-tibble = "==3.3.1"
r-ggplot2 = "==4.0.2"
r-pheatmap = "==1.0.13"
"r-this.path" = "==2.8.0"
r-tidyr = "==1.3.2"
r-patchwork = "==1.3.2"
r-forcats = "==1.0.1"
r-ggrepel = "==0.9.8"
r-stringr = "==1.6.0"
r-tidyselect = "==1.2.1"
r-future = "==1.69.0"
"r-future.apply" = "==1.20.2"
r-rjava = "==1.0.11"
r-cowplot = "==1.2.0"
r-ggpubr = "==0.6.3"
r-ggridges = "==0.5.7"
r-magrittr = "==2.0.4"
r-rstatix = "==0.7.3"
bioconductor-msbackendsql = "==1.10.1"
bioconductor-msexperiment = "==1.12.0"
bioconductor-spectra = "==1.20.1"
bioconductor-biobase = "==2.70.0"
bioconductor-protgenerics = "==1.42.0"
bioconductor-qfeatures = "==1.20.0"
bioconductor-summarizedexperiment = "==1.40.0"
bioconductor-limma = "==3.66.0"
bioconductor-complexheatmap = "==2.26.1"
bioconductor-metabocoreutils = "==1.18.1"
bioconductor-rdisop = "==1.70.0"
bioconductor-mscoreutils = "==1.22.1"
bioconductor-annotationhub = "==4.0.0"
bioconductor-metaboannotation = "==1.14.0"
bioconductor-xcms = "==4.8.0"
r-reticulate = "==1.46.0"
rdkit = "==2026.3.4"
pandas = ">=2.3.3,<3"
