Rscript .\met_disco.R ^
  --wd "C:/Users/wilhelm/Documents/MEGA/01_juniper/01_arbete/01_projekt/03_psm" ^
  --data_path "input_data" ^
  --meta_file "input_data\metadata_filtered.csv" ^
  --biotransf_file "biotransformations.csv" ^
  --output "apiin_bu" ^
  --internal_standard "C7H8O2" ^
  --adduct "[M-H]-" ^
  --ppm_global 15 ^
  --bw_first_grouping 3 ^
  --bw_second_grouping 0.5 ^
  --seed 123 ^
  --cores 10