---
output-dir: /Users/wilhelm/Proton/01_juniper/01_arbete/07_presentationer/260409_srn_lab_meeting
format:
  revealjs:
    theme: white
    width: 1920
    height: 1080
    embed-resources: true
    controls: true
    slide-number: true
    progress: true
    overview: true
    include-in-header:
      text: |
        <style>.hide-title h2 { position: absolute; left: -9999px; }</style>
---

```{r}
#| label: setup
#| echo: false
loc <- "/Users/wilhelm/Proton/01_juniper/01_arbete/07_presentationer/260409_srn_lab_meeting"
pdf_file <- "260409_srn_lab_meeting.pdf"
pptx_file <- "260409_srn_lab_meeting.pptx"

# Convert PDF to SVGs
slide_dir <- file.path(loc, "slides")
dir.create(slide_dir, showWarnings = FALSE)
system2("pdf2svg", c(file.path(loc, pdf_file), file.path(slide_dir, "slide-%d.svg"), "all"))

library(ggplot2)
library(plotly)

# Setup reticulate
library(reticulate)
use_virtualenv(
  "/Users/wilhelm/Library/CloudStorage/ProtonDrive-wilhelm.sjoland@proton.me-folder/01_juniper/01_arbete/01_projekt/03_psm/powerpoint_env",
  required = TRUE
)
```

```{python}
#| echo: false
import os
from pptx import Presentation

prs = Presentation(os.path.join(r.loc, r.pptx_file))
titles = []
for slide in prs.slides:
    t = slide.shapes.title
    titles.append(t.text.strip() if t else "")
```

```{r}
#| echo: false
#| output: asis
titles <- py$titles
slides <- list.files(slide_dir, pattern = "\\.svg$", full.names = FALSE)
nums <- as.integer(gsub("\\D", "", slides))
slides <- slides[order(nums)]

for (i in 1:5) {
  path <- file.path(slide_dir, slides[i])
  title <- if (i <= length(titles) && nchar(titles[i]) > 0) titles[i] else ""
  cat(sprintf('\n## %s {background-image="%s" background-size="contain" .hide-title}\n\n', title, path))
}
```

## {background-image="`r file.path(slide_dir, slides[6])`" background-size="contain" .hide-title}
```{r}
#| echo: false

p <- mtcars %>%
  ggplot2::ggplot(
    ggplot2::aes(
      x = wt,
      y = mpg,
      color = factor(cyl),
      text = paste("Car:", rownames(mtcars))
    )
  ) +
  ggplot2::geom_point() +
  ggplot2::labs(x = "Weight", y = "MPG", color = "Cylinders") +
  ggplot2::theme_minimal()

plotly::ggplotly(p = p, tooltip = "text")

p2 <- mtcars %>%
  ggplot2::ggplot(
    ggplot2::aes(
      x = wt,
      y = mpg,
      color = factor(cyl),
      text = paste("Car:", rownames(mtcars))
    )
  ) +
  ggplot2::geom_point() +
  ggplot2::labs(x = "Weight", y = "MPG", color = "Cylinders") +
  ggplot2::theme_minimal()

plotly::ggplotly(p = p2, tooltip = "text")
```

```{r}
#| echo: false
#| output: asis
for (i in 7:length(slides)) {
  path <- file.path(slide_dir, slides[i])
  title <- if (i <= length(titles) && nchar(titles[i]) > 0) titles[i] else ""
  cat(sprintf('\n## %s {background-image="%s" background-size="contain" .hide-title}\n\n', title, path))
}
```
